#!/bin/sh

usage(){
	echo "$0 -a"
	echo "$0 -f"
}

if [ "$1" != "-a" -a "$1" != "-f" ]; then
    usage
fi

for dir in `ls -l | grep ^d | awk '{print $9}'`; do
	cd $dir
    echo "dir: $dir"
	if [ "$1" = "-a" ]; then
		./compile -a
	elif [ "$1" = "-f" ]; then
		./compile -f all
	fi
	cd ..
done
